name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          # Os directory where you want to cache it, Will be diff for diff OS.
          path: ~/.npm
          # Name of the file base on os and hash method.
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # If above name file not found then look for below prefix.
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true

      # Build and Deploy on push event
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy On Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain smart-goldfish.surge.sh
        env: 
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}